baseURL = "https://piever.github.io/simpleblog/"
languageCode = "en-us"
title = "Thoughts and things"
theme = "ananke"
publishDir = "docs"
pygmentscodefences= "true"


[params]
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  featured_image = "/images/panda.jpg"
  recent_posts_number = 4